#!/usr/bin/env python3
"""Generate the Anywhere native script and self-contained .amrs subscription."""
import argparse
import base64
import csv
import hashlib
import io
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]

ENTRY = r'''
  if (!ctx || ctx.phase !== "response" || ctx.method !== "GET" || ctx.status !== 200) return;
  var url = ctx.url;
  if (typeof url !== "string" || !URL_GUARD.test(url)) return;
  var bytes = ctx.body;
  var limit = 4 * 1024 * 1024;
  if (!(bytes instanceof Uint8Array) || bytes.byteLength === 0 || bytes.byteLength > limit) return;
  var headers = ctx.headers || [];
  for (var h = 0; h < headers.length; h++) {
    if (String(headers[h][0]).toLowerCase() === "content-type" &&
        !/^(?:text\/html|application\/xhtml\+xml)(?:\s*;|$)/i.test(String(headers[h][1]).trim())) return;
  }
  try {
    // Anywhere's decoder replaces invalid UTF-8; require a lossless round trip.
    var body = Anywhere.codec.utf8.decode(bytes);
    var roundTrip = Anywhere.codec.utf8.encode(body);
    if (roundTrip.length !== bytes.length) return;
    for (var b = 0; b < bytes.length; b++) if (bytes[b] !== roundTrip[b]) return;
    var updated = rewrite(body, url);
    if (updated === body) { log("未识别到可修复的播放区域，保留原响应"); return; }
    var output = Anywhere.codec.utf8.encode(updated);
    if (output.byteLength > limit) { log("改写结果超过大小限制，保留原响应"); return; }
    log("已替换播放区域");
    ctx.body = output;
  } catch (_) {
    // Keep the original byte array on decode/parse/encode failure.
    log("解析失败，保留原响应");
  }
}
'''


def render():
    source = (ROOT / "zmq.js").read_text(encoding="utf-8")
    start = source.index("  var URL_GUARD = ")
    end = source.index("  var result = {};", start)
    helpers = source[start:end]
    previous_log = '''  function log(message) {
    if (typeof console !== "undefined") console.log("[ZMQ] " + message);
  }'''
    native_log = '''  function log(message) {
    try { Anywhere.log.info("[ZMQ] " + message); } catch (_) {}
  }'''
    if helpers.count(previous_log) != 1:
        raise ValueError("The shared helper layout changed; review the Anywhere adapter.")
    helpers = helpers.replace(previous_log, native_log)
    if any(symbol in helpers for symbol in ["$done", "$response", "$request"]):
        raise ValueError("Loon entry-point symbols leaked into native Anywhere helpers.")
    guard = re.search(r"var URL_GUARD = /(.*)/i;", helpers).group(1)
    digest = hashlib.sha256(source.encode()).hexdigest()
    native = (
        "/*\n * ZMQ playback repair — Anywhere native process(ctx).\n"
        " * Generated by scripts/build-anywhere.py; do not edit this file directly.\n"
        f" * Shared zmq.js SHA-256: {digest}\n"
        " * Only ctx.body is modified. Unknown pages keep their original bytes.\n */\n"
        'function process(ctx) {\n  "use strict";\n'
        + helpers + ENTRY.lstrip("\n")
    )
    domains = json.loads((ROOT / "anywhere/zmq-domains.json").read_text())
    if not domains or domains != sorted(set(domains)):
        raise ValueError("Domain suffixes must be non-empty, sorted and unique.")
    for domain in domains:
        if not re.fullmatch(r"(?:zimuquan|zmqurl|zmqsite)\d*\.(?:top|com|uk)", domain):
            raise ValueError("Expected an explicit brand domain suffix, without wildcards.")
    row = io.StringIO(newline="")
    csv.writer(row, lineterminator="\n").writerow([
        1, 100, "(?i)" + guard.replace(r"\/", "/"),
        base64.b64encode(native.encode()).decode("ascii")
    ])
    amrs = (
        "# Generated by scripts/build-anywhere.py.\n"
        "# Import/subscribe in Anywhere > MITM, not Routing.\n"
        "# Suffixes cover subdomains. Anywhere does not support wildcard hostnames.\n"
        "name = 字母圈播放修复 - Anywhere\n"
        "hostname = " + ", ".join(domains) + "\n\n[Rule]\n" + row.getvalue()
    )
    return {"anywhere/zmq.js": native, "anywhere/zmq.amrs": amrs}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check generated files without writing.")
    args = parser.parse_args()
    for path, content in render().items():
        target = ROOT / path
        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Out of date: {path}; run python3 scripts/build-anywhere.py")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
        print(("Checked " if args.check else "Generated ") + path)
